### PR TITLE
Fix direction of statusbar message

### LINKED ISSUE #379: Scrambled statusbar message for files with RTL names
This image explains everything:

I couldn't find a way of showing the message correctly for both LTR and RTL layouts, especially with mixed strings (I even tried `0x202E` and `0x202D`).

### PR DESCRIPTION
**Pull request by SafaAlfulaij**
We are displaying the filename at the first in the statusbar, which means that if it's RTL and the locale is LTR, the whole text will get messed up, resulting in hard-to-read and wrong display of the name and the information.

Fixes #379

### CODE REVIEW

File: pcmanfm/tabpage.cpp [hunk 1]
```diff
@@ -470,15 +475,19 @@ void TabPage::onSelChanged() {
...
+                      .arg(encloseWithBidiMarks(fi->mimeType()->desc()))
+                      .arg(QString::fromUtf8(
+                          (!layoutDirection() == Qt::LeftToRight) ? "\u200f" : "\u200e"));
             }
             else {
-                msg = QString("\"%1\" %2")
-                      .arg(fi->displayName())
-                      .arg(fi->mimeType()->desc());
+                msg = QString("%3\"%1\" %3%2")
+                      .arg(encloseWithBidiMarks(fi->displayName())(
```
Comment (tsujan) [inline pcmanfm/tabpage.cpp]: This should be:
```cpp
.arg(encloseWithBidiMarks(fi->displayName()))
```

File: pcmanfm/tabpage.cpp [hunk 2]
```diff
@@ -470,15 +475,19 @@ void TabPage::onSelChanged() {
...
+                      .arg(encloseWithBidiMarks(fi->mimeType()->desc())
```
Comment (tsujan) [inline pcmanfm/tabpage.cpp]: This should be:
```cpp
.arg(encloseWithBidiMarks(fi->mimeType()->desc()))
```

**Comment by tsujan** [comment]
Apart from the above typos, this is what I get when I rename a file by first typing "ها" an then "ha", with a space between them (and with LTR layout/locale):

ha

Please see the difference between the file name and what is shown on the status-bar. I think that such names were shown correctly with my closed PR but I may be wrong because it was a long time ago.

**Comment by tsujan** [comment]
In my opinion, if the above typos are corrected, this will be a good approach. The above-mentioned problem is negligible if one sees the same thing in Dolphin, for example ;)

File: pcmanfm/tabpage.h [hunk 3]
```diff
@@ -200,6 +200,10 @@ class TabPage : public QWidget {
 
     void setCustomizedView(bool value);
 
+protected:
+    // Adds bidi marks (RLM/LRM) around the text for the statusbar.
+    QString encloseWithBidiMarks(QString text);
+
```
Comment (tsujan) [inline pcmanfm/tabpage.h]: This can be added to the `private:` as:
```cpp
QString encloseWithBidiMarks(const QString& text);
```

**Comment by SafaAlfulaij** [comment]
Sorry, by mistake!

I think now even the cases that we said not to support are supported now :D

**Comment by tsujan** [comment]
> I think now even the cases that we said not to support are supported

Yes, the code seems to do that; will test it later.

File: pcmanfm/tabpage.h [hunk 4]
```diff
@@ -217,6 +217,9 @@ protected Q_SLOTS:
     void freeFolder();
     QString formatStatusText();
 
+    // Adds bidi marks (RLM/LRM/RLE/LRE/POP) around the text for the statusbar.
+    QString encloseWithBidiMarks(QString& text);
+
```
Comment (tsujan) [inline pcmanfm/tabpage.h]: A `const` is missing from the argument, which results in:
```
error: binding reference of type ‘QString&’ to ‘const QString’ discards qualifiers
```
Please always try to compile the branch before committing! Thanks!

Comment (SafaAlfulaij) [reply pcmanfm/tabpage.h]: I did, but forgot about this pointers thing!
_I actually can't understand pointers to the deep :)_

**Comment by tsujan** [comment]
Now it solves the problem completely. GTM.

The same conclusion, here: https://github.com/lxde/pcmanfm-qt/pull/382/files, but this is cleaner.

Apparently, wherever quotes, parentheses, brackets, etc. are used inside a potentially LTR-RTL mixed string, this method should be used. Dolphin has a similar issue.

File: pcmanfm/tabpage.h (hunk 4 above)
Comment (tsujan) [reply pcmanfm/tabpage.h]: It's good. I'll fix small problems after merging but I can't find any now.

Comment (tsujan) [reply pcmanfm/tabpage.h]: Oh, found one, which isn't small. This:
```cpp
(!layoutDirection() == Qt::LeftToRight) ? "\u200f" : "\u200e"
```
You mean the following; don't you?
```cpp
layoutDirection() == Qt::RightToLeft ? "\u200f" : "\u200e"
```
Please fix them and test the result!
